services:
  profile:
    image: redis
    volumes:
      - me:/data

  avatar:
    image: ghcr.io/infratify/arena-avatar
    ports:
      - "8080:8080"
    environment:
      NAME: ikhwannaufal
      COLOR: magenta
      SERVER: 13.212.241.150:3000
    depends_on:
      - profile

volumes:
  me:
